services:
  backend_dev:
    build:
      context: ./backend
      target: dev
    container_name: ai-overhaul-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:rw
      - ./backend/alembic:/app/alembic:rw
      - ./backend/alembic.ini:/app/alembic.ini:ro
      - ./backend/data:/app/data
    environment:
      - PYTHONPATH=/app
      - AIO_DEVMODE=1
      - STASH_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJza2kyMyIsImlhdCI6MTY2OTA2MjU4NCwic3ViIjoiQVBJS2V5In0.0QWitnVF0c0n8vjKDXN3c1Of7ZDreOyWg3iUcjlVzYw
      - STASH_INTERNAL_URL=http://host.docker.internal:3000
    command: python -m app.dev_entrypoint

  # If you prefer to run the dev container from the published image (no live reload),
  # replace `build:` above with:
  # image: ghcr.io/skier233/stash-ai-server:latest

  backend_prod:
    image: ghcr.io/skier233/stash-ai-server:latest
    container_name: ai-overhaul-backend-prod
    ports:
      - "8000:8000"
    environment:
      - STASH_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJza2kyMyIsImlhdCI6MTY2OTA2MjU4NCwic3ViIjoiQVBJS2V5In0.0QWitnVF0c0n8vjKDXN3c1Of7ZDreOyWg3iUcjlVzYw
      - STASH_INTERNAL_URL=http://host.docker.internal:3000
      - AI_SERVER_HOST=0.0.0.0
      - AI_SERVER_PORT=8000
      - AI_SERVER_PLUGINS_DIR=/app/plugins
    volumes:
      - ./backend/data:/app/data:rw
      - ./backend/plugins:/app/plugins:rw
