version: '3.9'
services:
  backend:
    build:
      context: ./backend
    container_name: ai-overhaul-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:rw
      - ./backend/alembic:/app/alembic:rw
      - ./backend/alembic.ini:/app/alembic.ini:ro
      - ./backend/data:/app/data
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
