name: Release (wheels -> PyPI -> GHCR image)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  determine:
    name: Determine tag + version
    runs-on: ubuntu-latest
    outputs:
      is_release: ${{ steps.set.outputs.is_release }}
      tag: ${{ steps.set.outputs.tag }}
      version: ${{ steps.set.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set
        run: |
          REF="${GITHUB_REF}"
          if [[ "$REF" == refs/tags/v* ]]; then
            TAG="${REF#refs/tags/}"
            build-wheel:
              name: Build wheel (universal)
              runs-on: ubuntu-latest
              needs: determine
              if: needs.determine.outputs.is_release == 'true'
              steps:
                - uses: actions/checkout@v4
                  with:
                    fetch-depth: 0
                - name: Set up Python 3.12
                  uses: actions/setup-python@v5
                  with:
                    python-version: '3.12'
                - name: Sync version from tag
                  env:
                    VERSION: ${{ needs.determine.outputs.version }}
                  run: |
                    echo "Setting backend/pyproject.toml version to $VERSION"
                    python - <<'PY'
                    import pathlib, os, re
                    p=pathlib.Path('backend/pyproject.toml')
                    s=p.read_text(encoding='utf8')
                    v=os.environ['VERSION']
                    s=re.sub(r'(?m)^version\s*=\s*"[^"]+"', f'version = "{v}"', s)
                    p.write_text(s, encoding='utf8')
                    print('Updated version ->', v)
                    PY
                - name: Install build tooling
                  run: python -m pip install --upgrade pip setuptools wheel build
                - name: Build wheel
                  working-directory: backend
                  run: python -m build --wheel
                - name: Show dist contents
                  run: ls -l backend/dist
                - name: Upload wheel artifact
                  uses: actions/upload-artifact@v4
                  with:
                    name: wheel
                    path: backend/dist/*.whl
          s=p.read_text(encoding='utf8')
          v=os.environ['VERSION']
          s=re.sub(r'(?m)^version\s*=\s*"[^"]+"', f'version = "{v}"', s)
          p.write_text(s, encoding='utf8')
          print('Updated version ->', v)
          PY
      - name: Install build tooling
        run: python -m pip install --upgrade pip setuptools wheel build
      - name: Build wheel
        working-directory: backend
        run: |
          python -m build --wheel
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: backend/dist/*.whl

  publish:
    name: Publish wheel to PyPI
    runs-on: ubuntu-latest
    needs: [determine, build-wheel]
    if: needs.determine.outputs.is_release == 'true'
    steps:
      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist_dl
      - name: List wheel
        run: ls -l dist_dl
      - name: Validate wheel version
        env:
          VERSION: ${{ needs.determine.outputs.version }}
        run: |
          python - <<'PY'
          import os, zipfile, sys, glob
          v=os.environ['VERSION']
          bad=0
          for w in glob.glob('dist_dl/*.whl'):
            with zipfile.ZipFile(w) as z:
              meta=[n for n in z.namelist() if n.endswith('METADATA')]
              if not meta: print('No METADATA in', w); bad+=1; continue
              text=z.read(meta[0]).decode()
              for line in text.splitlines():
                if line.startswith('Version:'):
                  got=line.split(':',1)[1].strip()
                  if got!=v:
                    print('Mismatch', w, got, '!=', v); bad+=1
                  else:
                    print('OK', w, got)
                  break
          sys.exit(bad)
          PY
      - name: Install twine
        run: python -m pip install --upgrade twine
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist_dl/*.whl

  image:
    name: Build & push GHCR image
    runs-on: ubuntu-latest
    needs: [determine, publish]
    if: needs.determine.outputs.is_release == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          target: runtime
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/stash-ai-server:${{ needs.determine.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/stash-ai-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
